"""端口定义：时钟、标识生成器、仓储协议。

应用服务只依赖这些协议；SQLite 是默认适配，测试可注入内存假实现或固定时钟。
"""
from __future__ import annotations

from datetime import datetime
from typing import Protocol, runtime_checkable

from ..domain.entities import Challenge, Evidence, Review, ReviewVersion


@runtime_checkable
class Clock(Protocol):
    def now(self) -> datetime:
        """返回当前 UTC 时间（必须带时区）。"""
        ...


@runtime_checkable
class IdGenerator(Protocol):
    def new_id(self, prefix: str = "") -> str:
        ...


@runtime_checkable
class Repository(Protocol):
    # -- review -------------------------------------------------------------
    def insert_review(self, review: Review) -> None: ...

    def get_review(self, review_id: str) -> Review | None: ...

    def list_reviews(self) -> list[Review]: ...

    # -- evidence -----------------------------------------------------------
    def insert_evidence(self, evidence: Evidence) -> None: ...

    def get_evidence(self, evidence_id: str) -> Evidence | None: ...

    def list_evidence(self, review_id: str) -> list[Evidence]: ...

    def list_evidence_after(self, review_id: str, cursor: int) -> list[Evidence]: ...

    def find_evidence_by_fingerprint(self, review_id: str, fingerprint: str) -> Evidence | None: ...

    # -- version ------------------------------------------------------------
    def insert_version(self, version: ReviewVersion) -> None: ...

    def update_version(self, version: ReviewVersion) -> None: ...

    def get_version(self, version_id: str) -> ReviewVersion | None: ...

    def get_version_by_seq(self, review_id: str, seq_no: int) -> ReviewVersion | None: ...

    def list_versions(self, review_id: str) -> list[ReviewVersion]: ...

    def latest_version(self, review_id: str) -> ReviewVersion | None: ...

    def list_computing_versions(self) -> list[ReviewVersion]: ...

    # -- challenge ----------------------------------------------------------
    def insert_challenge(self, challenge: Challenge) -> None: ...

    def update_challenge(self, challenge: Challenge) -> None: ...

    def get_challenge(self, challenge_id: str) -> Challenge | None: ...

    def list_challenges(self, review_id: str | None = None) -> list[Challenge]: ...

    # -- 续算状态 -----------------------------------------------------------
    def save_compute_state(self, version_id: str, cursor: int, states: dict) -> None: ...

    def get_compute_state(self, version_id: str) -> tuple[int, dict] | None: ...

    def delete_compute_state(self, version_id: str) -> None: ...

    # -- 事务 ---------------------------------------------------------------
    def begin_immediate(self) -> "Transaction": ...


class Transaction(Protocol):
    def __enter__(self) -> "Transaction": ...

    def __exit__(self, exc_type, exc, tb) -> None: ...

    def commit(self) -> None: ...

    def rollback(self) -> None: ...
